name:                ewe
version:             0.1.0.0
github:              "1computer1/ewe"
license:             MIT
author:              "1Computer"
maintainer:          "onecomputer00@gmail.com"
copyright:           "2019 1Computer"

extra-source-files:
- README.md

synopsis:            Language for the lambda calculus
category:            Language
description:         Please see the README

default-extensions:
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- OverloadedStrings
- TypeApplications
- TypeFamilies
- ViewPatterns

dependencies:
- base
- containers
- megaparsec
- mtl
- text
- transformers

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: app
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O
  dependencies:
    - ewe
    - optparse-applicative
    - repline
